/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "stm32f4xx.h"

int main(void) {

	//button config
	RCC -> AHB1ENR |= (1<<2);
	GPIOC -> MODER &= ~(3<<(13*2));
	GPIOC -> PUPDR &= ~(3<<(13*2));
	GPIOC -> PUPDR |= (3<<(13*2)); //pull up

	//led config
	RCC->AHB1ENR |= (1 << 0);

	GPIOA->MODER &= ~(3 << (5 * 2));
	GPIOA->MODER |= (1 << (5 * 2));

	GPIOA->OTYPER &= ~(1 << 5);

	GPIOA->OSPEEDR |= (3 << (5 * 2));

	GPIOA->PUPDR &= ~(3 << (5 * 2));

	while (1) {

		if (!(GPIOC->IDR & (1<<13))) {
			GPIOA->ODR |= (1 << 5);
		} else {
			GPIOA->ODR &= ~(1 << 5);
		}

	}
}
